baseURL = "https://branko3000.de"
languageCode = "en-us"
title = "Branko 3000"
defaultContentLanguage = 'de'
[blackfriday]
	hrefTargetBlank = true
[params]
description = 'Ruf mich vor der Arbeit an, ich battle dich in Shorts'
news = [
["Check out ABC*-Festival","https://abcfestival.de"],
["24/7 vor deinem Haus wie OG Keemo","/"],
["Ruf mich vor der Arbeit an, ich battle dich in Shorts","/"],
]
eggs = [
  "",
  "666"
]
[menu]
[[menu.main]]
identifier = "kontakt"
name = "Kontakt"
url = "mailto:johannes.hassenstein@pm.me"
weight = 1
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/branko3000"
weight = 2
