baseURL = "https://johassenstein.de"
languageCode = "de-de"
title = "johannes hassenstein"
defaultContentLanguage = 'de'
disableKinds = [ "RSS", "sitemap", "robotsTXT"]
timeout = 120000
[blackfriday]
	hrefTargetBlank = true
[taxonomies]

[params]
