baseURL = "https://johassenstein.de"
languageCode = "de-de"
title = "Johannes Hassenstein"
defaultContentLanguage = 'de'
disableKinds = [ "RSS", "sitemap", "robotsTXT"]
timeout = 120000
[blackfriday]
	hrefTargetBlank = true
[taxonomies]
tag = "tags"
[params]
description = "I create interactive spaces with love and code"
