baseURL = "https://branko3000.de"
languageCode = "de-de"
title = "DREITAUSEND"
defaultContentLanguage = 'de'
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
[blackfriday]
	hrefTargetBlank = true
[params]
description = 'Ruf mich vor der Arbeit an, ich battle dich in Shorts'
background = '#ffffff'
color = '#000000'
news = [
["Check out ABC*-Festival","https://abcfestival.de"],
["Ruf mich vor der Arbeit an, ich battle dich in Shorts","/"]
]
